#pragma once

#define VERSION_MAJOR 1
#define VERSION_MINOR 4
#define VERSION_PATCH 0

#define STRINGIFY_(x) #x
#define STRINGIFY(x)  STRINGIFY_(x)
#define VERSION       STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR) "." STRINGIFY(VERSION_PATCH)
